### ISSUE TITLE
Asynchronous initialization support?

### ISSUE THREAD

**Issue by lzhoucs** [dojo/compose#100] opened 2016-11-11 04:01 UTC
When creating an object from factory, it is possible to perform some async operations during initialization, and the object's state as well as its behaviors may depend on such async operations being done first. Consider the following code:
```typescript
const createFoo = compose({
    foo(this: any) {
        const state = instanceStateMap.get(this);
        // do things with `state.foobar`
    }
}, (instance) => {
    asyncOperation().then((response) => {
        instanceStateMap.set(instance, {
            foobar: response.foobar
        })
    })
})
const foo1 = createFoo();
foo1.foo();
```
The code above may not work since by the time `foo()` is called, `state.foobar` may not be available yet. A workaround we have used in `dojo/stores`, is to [maintain an initial promise as part of the state](https://github.com/dojo/stores/blob/master/src/store/createStore.ts#L194), the downside of this approach is we need to [deal with the promise everywhere](https://github.com/dojo/stores/blob/master/src/store/createStore.ts#L172-L174) the 'remote state' is needed.

I wonder if it makes sense to just return the promise to the compose factory, and let it manage the promise for us, similar to how intern works with the async tests where a promise can be returned. 

This applies to mixins as well.

I am just throwing out an idea, please skip it if it doesn't make much sense. :smile:

**Comment by kitsonk** [comment] 2016-11-11 07:31
Essentially a dupe of #54.

There is some discussion in that ticket of why that might be a challenge too.  For widgets, we essentially decided on making sure things are reactive, that not having the state would not be a problem and once the state was there, it would invalidate it.

The biggest challenge is that while initialisation could be managed async, the expectation when you create something, that it is "there".  In your above example, you would then want to do something like this:

``` ts
const p = createFoo();

p.then((foo1) => {
    foo1.foo();
});
```

Which just feels like a challenge.  Even with `async` ... `await` it would still feels like that is a lot of overhead.

**Comment by lzhoucs** [comment] 2016-11-11 08:25
Yeah, I can see the challenge too. But at the very least, the code above seems a bit cleaner than handling promises in every function where the state is needed.

Sorry I should have seen #54 before creating this one. Please feel free to close it.

**Comment by kitsonk** [comment] 2016-11-11 09:56
Let's move the discussion over there.

**Closed as completed by kitsonk** 2016-11-11 09:56 UTC
Labels: discussion
